language: node_js
node_js:
  - "8.12.0"
branches:
  only:
  - master
  - develop
after_success: yarn coverage
notifications:
  email:
    recipients:
      - swzyocowboy@icloud.com
    on_success: never
    on_failure: always
