language: node_js
node_js:
  - "10.13.0"
  - "8.12.0"
  - "7.10.1"
cache:
  yarn: true
branches:
  only:
  - master
  - develop
after_success: yarn coverage
notifications:
  email:
    recipients:
      - swzyocowboy@icloud.com
    on_success: never
    on_failure: always
